[PRMT-1994] Made assume ci role script fail on aws failure

diff --git a/utils/aws-helpers b/utils/aws-helpers
--- a/utils/aws-helpers
+++ b/utils/aws-helpers
@@ -11,7 +11,7 @@ function create_build_trace_id {
     git_hash=$(echo $GO_REVISION_GIT | cut -c 1-8)
     candidate_build_trace_id="$GO_PIPELINE_NAME@$GO_PIPELINE_COUNTER@$GO_STAGE_NAME@$GO_STAGE_COUNTER@$GO_JOB_NAME@$git_hash"
     length_to=${#candidate_build_trace_id}
-    length_from=$((length_to-63))
+    length_from=$((length_to-62))
 
     export BUILD_TRACE_ID=$(echo "$candidate_build_trace_id" | cut -c "$length_from"-"$length_to")
   fi
@@ -44,6 +44,13 @@ function _assume-ci-agent-role {
 
     echo "Build trace ID: $BUILD_TRACE_ID"
     json="$(aws sts assume-role --role-arn "$desired_role_arn" --role-session-name "$BUILD_TRACE_ID")"
+
+    if [ $? != 0 ]; then
+      >&2 echo "Failed assuming role $desired_role_arn"
+      exit 5
+    else
+      echo "Successfully assumed role $desired_role_arn"
+    fi
 
     export AWS_ACCESS_KEY_ID="$(echo "$json" | jq -r .Credentials.AccessKeyId)"
     export AWS_SECRET_ACCESS_KEY="$(echo "$json" | jq -r .Credentials.SecretAccessKey)"
