[PRMT-1994] Normalised cases to use snake case

diff --git a/utils/aws-helpers b/utils/aws-helpers
--- a/utils/aws-helpers
+++ b/utils/aws-helpers
@@ -46,14 +46,14 @@ function configure_docker_repository_uri {
   export REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/$IMAGE_REPO_NAME
 }
 
-function assume-ci-agent-role {
+function assume_ci_agent_role {
   CURRENT_DIR=$(pwd)
   cd "$SCRIPT_DIR"
   eval $(dojo -image "$DOJO_IMAGE_VERSION" "./aws-helpers assume_ci_agent_role $1")
   cd "$CURRENT_DIR"
 }
 
-function _assume-ci-agent-role {
+function _assume_ci_agent_role {
   unset AWS_ACCESS_KEY_ID
   unset AWS_SECRET_ACCESS_KEY
   unset AWS_SESSION_TOKEN
@@ -91,13 +91,13 @@ function promote_docker_image {
   IMAGE_TAG=${COMMIT_HASH}
   IMAGE_TEMPORARY_NAME="$IMAGE_REPO_NAME:$IMAGE_TAG"
 
-  assume-ci-agent-role "$environment_from"
+  assume_ci_agent_role "$environment_from"
   configure_docker_repository_uri
   echo "Pulling the image from $REPOSITORY_URI:$IMAGE_TAG.."
   docker pull "$REPOSITORY_URI:$IMAGE_TAG"
   docker tag "$REPOSITORY_URI:$IMAGE_TAG" "$IMAGE_TEMPORARY_NAME"
 
-  assume-ci-agent-role "$environment_to"
+  assume_ci_agent_role "$environment_to"
   configure_docker_repository_uri
   docker tag "$IMAGE_TEMPORARY_NAME" "$REPOSITORY_URI:$IMAGE_TAG"
   echo "Pushing the image to $REPOSITORY_URI:$IMAGE_TAG.."
@@ -110,10 +110,14 @@ function promote_docker_image {
 
 command="$1"
 case "${command}" in
-  assume-ci-agent-role)
-    _assume-ci-agent-role $2
+  assume_ci_agent_role)
+    _assume_ci_agent_role $2
     echo "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
     echo "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
     echo "export AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN"
+  ;;
+  *)
+    echo "Invalid command: '${command}'"
+    exit 1
   ;;
 esac
