PRMT-1994 added release cycle for the aws-helpers script

diff --git a/utils/aws-helpers b/utils/aws-helpers
--- a/utils/aws-helpers
+++ b/utils/aws-helpers
@@ -19,6 +19,16 @@ function create_build_trace_id {
   fi
 }
 
+function get_aws_ssm_secret {
+  secret_id=$1
+  json=$(dojo -image "$DOJO_IMAGE_VERSION" "aws ssm get-parameter --with-decryption --region eu-west-2 --name $secret_id")
+  if [ $? != 0 ]; then
+    >&2 echo "Failed to obtain AWS secret from SSM: $secret_id"
+    exit 5
+  fi
+  echo $json | jq -r ".Parameter.Value"
+}
+
 function _get_aws_ssm_secret {
   secret_id=$1
   json=$(aws ssm get-parameter --with-decryption --region "eu-west-2" --name $secret_id)
